### ISSUE TITLE
Grass growing in Tilled Soils blocks automatic crop harvest

### ISSUE THREAD

**Issue by Pichu0102** [sam23694/TilledSoil#1]
Occasionally, when loading a save with Tilled Soil, crops on tilled soil may also have grass growing in the same tile. If this happens, colonists will not automatically harvest the crop, and you'll get a notice eventually when it rots. You have to select and then hit harvest to manually tell them to harvest the crop when this happens. Only seems to occur when loading files.
![294100_20170126073435_1](https://cloud.githubusercontent.com/assets/4944941/22331661/a83220b2-e39a-11e6-8acc-c52c82e43a1b.png)

An example bugged crop with grass.

A save, output log, and modconfig are attached.

[tilledsoil-1-26-2017-bugreport.zip](https://github.com/sam23694/TilledSoil/files/732271/tilledsoil-1-26-2017-bugreport.zip)

The Rimworld version is A16.

**Comment by sam23694** [comment]
With such a long list of mods it is very difficult to narrow down the cause of this issue. However I can tell you tilled soil only adds two natural floor types and does not modify the core logic with an assembly. That means you have another mod that changes something related to plants and their interaction. I recommend looking at other mods in your list related to plant growth.

Also, while I appreciate the feedback I recommend posting issues like this on the forum or on the Steam thread. Issues here should be reserved for repository problems and anything related to pull requests.
